@baseUrl = http://localhost:3002/api/v2/users

@validEmail = o@o.com
@validPassword = oooooooo

### createUser >> test Login
POST {{baseUrl}}/
Content-Type: application/json

{
    "username": "ong",
    "email": "{{validEmail}}",
    "password": "{{validPassword}}",
    "role": "admin"
}


### loginUser where're my token????? 
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "{{validPassword}}"
}

### getAuthMe >> Cookie+jwt
GET {{baseUrl}}/auth/me

### logoutUser >> Clear Cookie
POST {{baseUrl}}/auth/logout