@baseUrl = http://localhost:3002/api/v2/users

@validEmail = o@o.com
@validPassword = oooooooo

### 1 login - success
POST {{baseUrl}}/pg/login
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "{{validPassword}}"
}

### 2 login - missing credential - 400
POST {{baseUrl}}/pg/login
Content-Type: application/json

{
    "email": "{{validEmail}}"
}

### 3 login - wrong password -400
POST {{baseUrl}}/pg/login
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "wrongpassword"
}

### 4 - login - user not found
POST {{baseUrl}}/pg/login
Content-Type: application/json

{
    "email": "doesnotexist@example.com",
    "password": "password123"
}

### 5 - check session - success - run after login, cookie auto send
### The REST Client stores the Set-Cookie header from request #1 automatically.
GET {{baseUrl}}/pg/auth/me

### 6 - check session - no token - 401
GET {{baseUrl}}/pg/auth/me
Cookie: accessToken=

### 7 - check session - expire/invalid 500
GET {{baseUrl}}/pg/auth/me
Cookie: accessToken=this.is.not.a.valid.jwt

### 8 - logout - success
POST {{baseUrl}}/pg/auth/logout

### 9 - check session - after logout - 401
GET {{baseUrl}}/pg/auth/me