### Read all users
GET http://localhost:3002/api/v2/users

### Create a new user
POST http://localhost:3002/api/v2/users
Content-Type: application/json

    {
        "id": "1",
        "username": "araragi",
        "email": "a@a.com",
        "password": "aaaaaaaa"
    }

    # {
    #     "id": "2",
    #     "username": "beniyakumo",
    #     "email": "b@b.com",
    #     "password": "bbbbbbbb"
    # }

    # {
    #     "id": "3",
    #     "username": "chinnosuke",
    #     "email": "c@c.com",
    #     "password": "cccccccc"
    # }

    # {
    #     "id": "4",
    #     "username": "dorikawa",
    #     "email": "d@d.com",
    #     "password": "dddddddd"
    # }

    # {
    #     "id": "5",
    #     "username": "edogawa",
    #     "email": "e@e.com",
    #     "password": "eeeeeeee"
    # }

    # {
    #     "id": "6",
    #     "username": "fukuoka",
    #     "email": "f@f.com",
    #     "password": "ffffffff"
    # }

    # {
        
    #     "username": "haruka",
    #     "email": "h@h.com",
    #     "password": "hhhhhhhh"
    # }
# {
#         "username": "jounouchi",
#         "email": "j@j.com",
#         "password": "jjjj"
#     }
# {
#         "username": "kuroko",
#         "email": "k@k.com",
#         "password": "kkkkkkkk"
#     }
# {
#         "username": "nene",
#         "email": "n@n.com",
#         "password": "nnnnnnnn"
#     }

### Update a user
PUT http://localhost:3002/api/v2/users/6a0b27439592bd028f3ec697
Content-Type: application/json

{
    "username": "xenoses",
    "email": "x@x.com",
    "password": "xxxxxxxx"
}

### Delete a user
DELETE http://localhost:3002/api/v2/users/6a0d499c59c380ff3072bfc1